Traceback (most recent call last):
  File "printer.py", line 91, in <module>
    for repo in g.get_user().get_repos() :
  File "/home/pi/.local/share/virtualenvs/github-issue-thermal-printer-Eu7rDIx2/lib/python3.7/site-packages/github/PaginatedList.py", line 64, in __iter__
    newElements = self._grow()
  File "/home/pi/.local/share/virtualenvs/github-issue-thermal-printer-Eu7rDIx2/lib/python3.7/site-packages/github/PaginatedList.py", line 76, in _grow
    newElements = self._fetchNextPage()
  File "/home/pi/.local/share/virtualenvs/github-issue-thermal-printer-Eu7rDIx2/lib/python3.7/site-packages/github/PaginatedList.py", line 201, in _fetchNextPage
    headers=self.__headers
  File "/home/pi/.local/share/virtualenvs/github-issue-thermal-printer-Eu7rDIx2/lib/python3.7/site-packages/github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/pi/.local/share/virtualenvs/github-issue-thermal-printer-Eu7rDIx2/lib/python3.7/site-packages/github/Requester.py", line 286, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
